SELECT 
    a.ANIMAL_ID,
    CASE 
        WHEN a.ANIMAL_SEX = 'M' THEN 'Male'
        WHEN a.ANIMAL_SEX = 'F' THEN 'Female'
    END AS ANIMAL_SEX,
    a.ANIMAL_ADDED,
    a.SPEC_GENUS || ' ' || a.SPEC_NAME AS scientific_name,
    s.SPEC_POPULAR_NAME
FROM
    ES.ANIMAL a
    LEFT JOIN ES.SPECIES s ON a.SPEC_GENUS = s.SPEC_GENUS AND a.SPEC_NAME = s.SPEC_NAME
WHERE 
    a.BREVENT_ID IS NOT NULL
    AND (s.SPEC_POPULAR_NAME LIKE '%RHINOCEROS%' OR s.SPEC_POPULAR_NAME LIKE '%HIPPOPOTAMUS%')
    AND TO_CHAR(a.ANIMAL_ADDED, 'YYYY') < '2020'
ORDER BY 
    s.SPEC_POPULAR_NAME, 
    ANIMAL_SEX, 
    a.ANIMAL_ID DESC;
