SELECT 
    c.CENTRE_NAME AS "Centre Name",
    COUNT(e.EXCHANGE_NO) AS "Number of Exchanges(To/From)"
FROM 
    ES.EXCHANGE e
JOIN 
    ES.CENTRE c ON e.EXCHANGE_FROM_CENTRE_ID = c.CENTRE_ID OR e.EXCHANGE_TO_CENTRE_ID = c.CENTRE_ID
GROUP BY 
    c.CENTRE_NAME
ORDER BY 
    c.CENTRE_NAME;
